config/routes.rb
Rails.application.routes.draw do

  resources :subdepartamentos

  get 'marcacion/index'

  resources :reqcargos

  resources :vacantes

  resources :prospectos

  resources :usuarios

  resources :empleados

  resources :turnos

  resources :fases

  resources :seccions

  resources :centro_costos

  resources :proyectos

  resources :cargos

  resources :departamentos

  resources :sucursals

  resources :sessions

  resources :marcacions do
    collection { post :import }
  end

  get 'login' => 'sessions#create', as: :login

  get 'logout' => 'sessions#destroy', as: :logout

  root 'welcome#index'

end

app/models/reqcargo.rb
class Reqcargo < ActiveRecord::Base
  belongs_to :cargo
end

app/controllers/reqcargos_controller.rb
class ReqcargosController < ApplicationController
  before_action :set_reqcargo, only: [:show, :edit, :update, :destroy]

  # GET /reqcargos
  # GET /reqcargos.json
  def index
    @reqcargos = Reqcargo.all
  end

  # GET /reqcargos/1
  # GET /reqcargos/1.json
  def show
    add_breadcrumb "Detalles", @reqcargos
  end

  # GET /reqcargos/new
  def new
    @reqcargo = Reqcargo.new
  end

  # GET /reqcargos/1/edit
  def edit
  end

  # POST /reqcargos
  # POST /reqcargos.json
  def create
    @reqcargo = Reqcargo.new(reqcargo_params)

    respond_to do |format|
      if @reqcargo.save
        format.html { redirect_to @reqcargo, notice: 'Reqcargo was successfully created.' }
        format.json { render :show, status: :created, location: @reqcargo }
      else
        format.html { render :new }
        format.json { render json: @reqcargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reqcargos/1
  # PATCH/PUT /reqcargos/1.json
  def update
    respond_to do |format|
      if @reqcargo.update(reqcargo_params)
        format.html { redirect_to @reqcargo, notice: 'Reqcargo was successfully updated.' }
        format.json { render :show, status: :ok, location: @reqcargo }
      else
        format.html { render :edit }
        format.json { render json: @reqcargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reqcargos/1
  # DELETE /reqcargos/1.json
  def destroy
    @reqcargo.destroy
    respond_to do |format|
      format.html { redirect_to reqcargos_url, notice: 'Reqcargo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reqcargo
      @reqcargo = Reqcargo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reqcargo_params
      params.require(:reqcargo).permit(:cargo_id, :nomrequis, :lactivo)
    end
end

app/helpers/reqcargos_helper.rb
module ReqcargosHelper
end

app/views/reqcargos/_form.html.haml
= form_for @reqcargo do |f|
  - if @reqcargo.errors.any?
    #error_explanation
      %h2= "#{pluralize(@reqcargo.errors.count, "error")} prohibited this reqcargo from being saved:"
      %ul
        - @reqcargo.errors.full_messages.each do |msg|
          %li= msg

  .row
    .col-sm-11
      .panel.panel-primary
        .panel-heading
          %h4.panel-title Datos
        .panel-body.form-horizontal
          .field.form-group.col-sm-4
            = f.label :Cargo, :class=> "control-label"
            = f.collection_select :cargo_id, Cargo.select("id, nombre").all, :id, :nombre, {}, {:class=> "form-control input-sm"}
          .field.form-group.col-sm-4
            = f.label :Requisito, :class=> "control-label"
            = f.text_field :nomrequis, :class=> "form-control input-sm"
          .field.form-group.col-sm-1
            = f.label :Requerido?, :class=> "control-label"
            = f.check_box :requerido, :class=> "form-control input-sm"
          .field.form-group.col-sm-1
            = f.label :Activo?, :class=> "control-label"
            = f.check_box :lactivo, :class=> "form-control input-sm"
        .panel-footer
          .actions
            = f.button(type: "submit", class: "btn btn-sm btn-primary") do
              Guardar
              %i.fa.fa-save

app/views/reqcargos/edit.html.haml
%h1 Editing reqcargo

= render 'form'

= link_to 'Show', @reqcargo
\|
= link_to 'Back', reqcargos_path

app/views/reqcargos/index.html.haml
%h3 Requisitos del Cargo

%table#datagrid.table.table-hover.table-condensed.table-responsive
  %thead
    %tr
      %th Cargo
      %th Requisito
      %th Requerido?
      %th Activo?
      %th Acciones

  %tbody
    - @reqcargos.each do |reqcargo|
      %tr
        %td= Cargo.find(reqcargo.cargo_id).nombre
        %td= reqcargo.nomrequis
        %td.centered
          - if reqcargo.requerido
            %i.fa.fa-check.text-success
          - else
            %i.fa.fa-times.text-danger
        %td.centered
          - if reqcargo.lactivo
            %i.fa.fa-check.text-success
          - else
            %i.fa.fa-times.text-danger
        %td.centered
          = link_to reqcargo do
            %i.fa.fa-search-plus.text-success{'title' => "Detalles"}
          \|
          = link_to edit_reqcargo_path(reqcargo) do
            %i.fa.fa-pencil.text-primary{'title' => "Editar"}
          \|
          = link_to reqcargo, method: :delete, data: { confirm: '¿Está Seguro?' } do
            %i.fa.fa-trash-o.text-danger{'title' => "Borrar"}

%br

= link_to new_reqcargo_path, :class=> "btn btn-primary btn-sm" do
  %i.fa.fa-plus.text-success
  Nuevo

app/views/reqcargos/new.html.haml
%h1 New reqcargo

= render 'form'

= link_to 'Back', reqcargos_path

app/views/reqcargos/show.html.haml
%p#notice= notice

.row
  .col-sm-11
    .panel.panel-primary
      .panel-heading
        %h4.panel-title Requisitos del Cargo
    .panel-body.form-horizontal
    .field.form-show.col-sm-4
      %Strong
        Cargo:
      %br
        = Cargo.find(@reqcargo.cargo_id).nombre
    .field.form-show.col-sm-4
      %Strong
        Nombre:
      %br
        = @reqcargo.nomrequis
    .field.form-show.col-sm-2
      %Strong
        Requerido:
      %br
        = @reqcargo.requerido
    .field.form-show.col-sm-2
      %Strong
        Activo:
      %br
        = @reqcargo.lactivo
    .col-sm-3
      %br
      %br
      = link_to 'Editar', edit_reqcargo_path(@reqcargo)
      |
      = link_to 'Regresar', reqcargos_path